appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: Xn/eYLZWj0qaP1LTYfI9LD0psgNSO4CTsuF+M3U+55DB/viZ4qVD+8XkEsIULcf0Znqt9O7Pd1u2nUcmzPtzbRC98wsWQFi3mmAFTfPvY+heB0OUesnM7SrdkPslhB0uTLZ68z8QNEYnv60gsNButPFeITXKVoSrEhtAwlgPQTXj2+0pA6LhG4dhGf7XHsOX6Z9G85pUvNMR78EihI4RuQ/LmX5jEPB98tp90jAqW6skEz5OCPJXERs2X4PyN06QLLwE8QVijHhFd1nWaybgLQlLKaJlrjGeLeX5yaue3bSom0fjb0zS+CqVVhYBTbDTzGuNWN+qSb3JoojrGGbzpIqDPXeOJTb8OoB4kgVNAf8zPeef73YS8LtfMxvsFoVMxG4AHKOKzI8Ur1T1r3CfSZda6e/qDfSGYLVKb2tNwKs+JbbdDKzxiDXwD9xN8XTFRNDDl5LsVcmwEyw0hUsF5ZPw1IEJg5i/qVeETV2OIr8TXLSJzSIuIZGbboWOQwpPSsawFZvCYgZKX1OeOS5yb0aT2pFeqfSa8edFPc6/HjS5FHPPS5Luonpi+7lr0a6jN+pMoiM/FbttYPnUWamSZLShaLH7AQ95beGI1ZwU011cJ519cZnHdwLhPqQm+PkK/74FUAClk7rqeHTCK62UwF60BUYNZhz5ljkkJlxrx1E=}
conda_forge_output_validation: true
