travis:
  secure:
    BINSTAR_TOKEN: pvfc7GUTcpfD0mIUdi99MMiTcx/Km4KpLCoceKcjSZgjhGp9d4O6D9RcWNPL3Gobezay1kIHUU9DYn3KwxU3N2FK70ZcPnenaFCxJJ8TCREkwUC83kYz5YSoiFpYIv7Oenx4eTKxsRKlz8qi/lUS1Q+DrYZYMgZ9MStXawIvfpiu9swRcolu6s0/vhGgWfIym9ssE76bnLMWSsS07nlnYz8fwVm1/x+DSoxzrAoZqLeOKdmGE0efPCBJ/ECfyKLeNPqwftNSwn/y9WhJQti38P5WGymWIDBkJn+neDgkC37qf/3m2O8pVm2TEnR1X29DFu4LtcmvLZLGhj1xF1nNlPGDfuu84q22AQ01U6DBexotwqhNCMT4fkiEQM7MFOKgAAYu66z3C1IFKdZjDnVCFp6cjDMi9odARPGEyoN9vspSuikPmGilgUwfZ+8l4jVzsX8xcYgP+A4CBi2AMY7/Tv3tlfKYTyGBt7FpUHzUFbqfJyxt0mr+Nti0Cj2gloY5xxjqjy20mqtRe0h0UDzpB0wrkIxe2HB95ihdktM9L4uZiGC9O3vjLwIkqkllS55OBy4PRPBgN7+txiYiIWzGr0z4lWdxQVuP6ooy6uoROidjohgJldSBf/VN2lhLzfqYcL1zw/mFewJPcfykR+BtpfjyYaWVikc/hvqbRDMoZgM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
